# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

# Below works, but not on dev machine, so preferring to inject the correct domain instead
#"https://www.{default}/uploads/":
#    type: upstream
#    upstream: "strapi:http"

"https://www.{default}/":
    type: upstream
    upstream: "nuxt:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://backend.{default}/":
    type: upstream
    upstream: "strapi:http"
